//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRT
{
    using System;
    using System.Collections.Generic;
    
    public partial class iOrders
    {
        public int id { get; set; }
        public int product_id { get; set; }
        public string account_id { get; set; }
        public string order_delivery { get; set; }
        public string order_price { get; set; }
        public string product_name { get; set; }
    }
}
